const gigs = [
  "31 Jan 26\tThe Woodpecker, Raunds",
  "14 Mar 26\tThomas A Becket, Northampton",
  "20 Mar 26\tAxe & Compass, Ringstead - 8pm start",
  "21 Mar 26\tJoe's Bar, Higham Ferrers",
  "25 Apr 26\tCrown & Anchor, Northampton",
  "02 May 26\tHigham Works, Higham Ferrers",
  "16 May 26\tCharity gig, Yelden",
  "22 May 26\tTBC",
  "20 Jun 26\tLoddington Festival, Loddington",
  "27 Jun 26\tCharity gig, Riseley",
  "04 Jul 26\tRushden Cons, Rushden",
  "10 Jul 26\tGreen Dragon, Higham Ferrers",
  "11 Jul 26\tPrivate Function",
  "01 Aug 26\tBurton Latimer Band Club, Burton Latimer",
  "29 Aug 26\tHigham SAS, Higham Ferrers",
  "05 Sep 26\tJoe's Bar, Higham Ferrers",
  "11 Sep 26\tAxe & Compass, Ringstead 8pm start",
  "24 Oct 26\tCoach & Horses, Wellingborough",
  "27 Nov 26\tCarriage House TBC, Higham Ferrers",
  "28 Nov 26\tRushden Cons, Rushden",
  "18 Dec 26\tCrown & Anchor, Northampton",
  "19 Dec 26\tHigham SAS, Higham Ferrers"
];
